### ISSUE TITLE
Mysterious symbols in bitcoin price

### ISSUE THREAD

**Issue by wfenglund** [fsson/conky-wojakPriceIndicator#4]
When using the theme on my machine (manjaro i3 edition), weird symbols are appearing between the numbers  in the bitcoin price.

However, if I change row 36 in conky-config from:
`override_utf8_locale = false,`

to:
`override_utf8_locale = true,`

this issue is resolved. Would it be helpful to change this to `true` as a default or could that perhaps lead to other issues for other distros?

**Comment by fsson** [comment]
Tried it out successfully on my system (Ubuntu based), did a pullreq with the suggested change.
